#!/bin/bash

USER=`whoami`
HOST=`hostname -s`
DOMAIN=`hostname -d`
LOG_LEVEL=INFO
HBASE_VERSION=${HBASE_VERSION:-2.1.8}
SERVERS=${SERVERS:-3}
HBASE_HOME=${HBASE_HOME:-"/opt/hbase-${HBASE_VERSION}"}
SSH_PORT=${SSH_PORT:-}

isCUSTOM=${isCUSTOM:-false}

ulimit -n 65535

mkdir -p /opt/hbase-${HBASE_VERSION}/pids

echo "export HBASE_PID_DIR=/opt/hbase-${HBASE_VERSION}/pids" >> /opt/hbase-${HBASE_VERSION}/conf/hbase-env.sh
echo "export HBASE_MANAGES_ZK=false" >> /opt/hbase-${HBASE_VERSION}/conf/hbase-env.sh
echo "export JAVA_HOME=${JAVA_HOME}" >> /opt/hbase-${HBASE_VERSION}/conf/hbase-env.sh

function scan_ssh_key() {
    for (( i=1; i<=$SERVERS; i++ ))
    do
        ssh-keyscan -t rsa ${HOSTNAME//-*}-$((i-1)).${DOMAIN} -p ${SSH_PORT} >> ~/.ssh/known_hosts && ssh-keygen -H -f ~/.ssh/known_hosts
    done
}

if [ ${isCUSTOM} == "false" ]; then
	/usr/sbin/sshd

	until echo rcok | nc ${HOSTNAME//-*}-0.${DOMAIN} ${SSH_PORT}; do >&2 echo "Starting..." && sleep 1 ; done
	until echo rcok | nc ${HOSTNAME//-*}-1.${DOMAIN} ${SSH_PORT}; do >&2 echo "Starting..." && sleep 1 ; done
	until echo rcok | nc ${HOSTNAME//-*}-2.${DOMAIN} ${SSH_PORT}; do >&2 echo "Starting..." && sleep 1 ; done

	scan_ssh_key
fi


until /opt/hbase-${HBASE_VERSION}/bin/start-hbase.sh ; do >&2 echo "Starting..." && sleep 1 ; done
