---
apiVersion: v1
kind: Service
metadata:
  name: hbase-user-dev-01
  namespace: user
  labels:
    app: hbase
spec:
  ports:
  - port: 60030
    name: master
  - port: 60010
    name: web
  clusterIP: None
  selector:
    app: hbase
