apiVersion: v1
kind: ConfigMap
metadata:
  name: user-dev-hbase-cluster1
  namespace: user
data:
  hbase-site.xml: |-
    <configuration>

        <property>
          <name>hbase.cluster.distributed</name>
          <value>true</value>
        </property>

        <property>
          <name>hbase.zookeeper.quorum</name>
          <value>10.100.21.87:2181,10.100.21.88:2181,10.100.21.89:2181</value>
        </property>

        <property>
          <name>hbase.zookeeper.property.dataDir</name>
          <value>/data/hbase/zookeeperData</value>
        </property>

        <property>
          <name>hbase.zookeeper.property.clientPort</name>
          <value>2181</value>
        </property>

        <property>
          <name>hbase.tmp.dir</name>
          <value>/data/hbase/tmp</value>
        </property>

        <property>
          <name>hbase.rootdir</name>
          <value>hdfs://hdfs-user-dev-01/hbase</value>
        </property>

        <property>
          <name>hbase.master.info.port</name>
          <value>60010</value>
        </property>

        <property>
          <name>hbase.regionserver.info.port</name>
          <value>60030</value>
        </property>

        <property>
          <name>zookeeper.session.timeout</name>
          <value>120000</value>
        </property>

        <property>
          <name>hbase.regionserver.restart.on.zk.expire</name>
          <value>true</value>
        </property>

    </configuration>

  regionservers: |-
    10.100.21.87
    10.100.21.88
    10.100.21.89

  hdfs-site.xml: |-
    <configuration>

      <property>
        <name>dfs.nameservices</name>
        <value>hdfs-user-dev-01</value>
      </property>

      <property>
        <name>dfs.ha.namenodes.hdfs-user-dev-01</name>
        <value>nn1,nn2</value>
      </property>

      <property>
        <name>dfs.namenode.rpc-address.hdfs-user-dev-01.nn1</name>
        <value>10.100.21.87:8020</value>
      </property>

      <property>
        <name>dfs.namenode.rpc-address.hdfs-user-dev-01.nn2</name>
        <value>10.100.21.88:8020</value>
      </property>

      <property>
        <name>dfs.namenode.http-address.hdfs-user-dev-01.nn1</name>
        <value>10.100.21.87:50070</value>
      </property>

      <property>
        <name>dfs.namenode.http-address.hdfs-user-dev-01.nn2</name>
        <value>10.100.21.88:50070</value>
      </property>

      <property>
        <name>dfs.namenode.shared.edits.dir</name>
        <value>qjournal://10.100.21.87:8485;10.100.21.88:8485;10.100.21.89:8485/hdfs-user-dev-01</value>
      </property>

      <property>
        <name>dfs.client.failover.proxy.provider.hdfs-user-dev-01</name>
        <value>org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider</value>
      </property>

      <property>
        <name>dfs.ha.fencing.methods</name>
        <value>sshfence</value>
      </property>

      <property>
        <name>dfs.ha.fencing.ssh.private-key-files</name>
        <value>/root/.ssh/id_rsa</value>
      </property>

      <property>
        <name>dfs.replication</name>
        <value>3</value>
      </property>

      <property>
        <name>dfs.permissions.enabled</name>
        <value>false</value>
      </property>

      <property>
        <name>dfs.ha.automatic-failover.enabled</name>
        <value>true</value>
      </property>

      <property>
        <name>ha.zookeeper.quorum</name>
        <value>10.100.21.87:2181,10.100.21.88:2181,10.100.21.89:2181</value>
      </property>

      <property>
        <name>dfs.journalnode.edits.dir</name>
        <value>/data/jn/edits</value>
      </property>

      <property>
        <name>dfs.namenode.name.dir</name>
        <value>/data/nn/name</value>
      </property>

      <property>
        <name>dfs.datanode.data.dir</name>
        <value>/data/dn/data</value>
      </property>

      <property>
        <name>dfs.namenode.checkpoint.dir</name>
        <value>/data/nn/checkpoint</value>
      </property>

    </configuration>
