apiVersion: v1
kind: ConfigMap
metadata:
  name: user-dev-hbase-cluster1
  namespace: user
data:
  hbase-site.xml: |-
    <configuration>

        <property>
          <name>hbase.cluster.distributed</name>
          <value>true</value>
        </property>

        <property>
          <name>hbase.master</name>
          <value>60000</value>
        </property>

        <property>
          <name>hbase.zookeeper.quorum</name>
          <value>zk-0.zk-user-dev-01.user.svc.cluster.local:2181,zk-1.zk-user-dev-01.user.svc.cluster.local:2181,zk-2.zk-user-dev-01.user.svc.cluster.local:2181</value>
        </property>

        <property>
          <name>hbase.zookeeper.property.dataDir</name>
          <value>/data/hbase/zookeeperData</value>
        </property>

        <property>
          <name>hbase.zookeeper.property.clientPort</name>
          <value>2181</value>
        </property>

        <property>
          <name>hbase.tmp.dir</name>
          <value>/data/hbase/tmp</value>
        </property>

        <property>
          <name>hbase.master.info.port</name>
          <value>60010</value>
        </property>

        <property>
          <name>hbase.regionserver.info.port</name>
          <value>60030</value>
        </property>

        <property>
          <name>zookeeper.session.timeout</name>
          <value>120000</value>
        </property>

        <property>
          <name>hbase.regionserver.restart.on.zk.expire</name>
          <value>true</value>
        </property>

    </configuration>
